### ISSUE TITLE
Error on Debian 8 amd64

### ISSUE THREAD

**Issue by chiel1980** [dustinmhorvath/OneStopIDS#2]
Hello,

I get the following error on a clean install of debian 8 amd64:

```
norby setup (1/6) updating snorby configuration and getting dependencies...
Snorby setup (2/6) installing dependencies...
Snorby setup (3/6) bundle installing...
Snorby setup (4/6) setting up Snorby...
rake aborted!
There was an error while trying to load the gem 'devise'.
Gem Load Error is: ActiveSupport::Duration can't be coerced into Integer
Backtrace for gem load error is:
/usr/local/rvm/gems/ruby-2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:50:in `*'
/usr/local/rvm/gems/ruby-2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:50:in `days'
/usr/local/rvm/gems/ruby-2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:55:in `weeks'
/usr/local/rvm/gems/ruby-2.4.0/gems/devise-1.5.4/lib/devise.rb:121:in `<module:Devise>'
/usr/local/rvm/gems/ruby-2.4.0/gems/devise-1.5.4/lib/devise.rb:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/var/www/snorby/config/application.rb:12:in `<top (required)>'
/var/www/snorby/Rakefile:4:in `require'
/var/www/snorby/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/bin/rake:22:in `load'
/usr/local/rvm/gems/ruby-2.4.0/bin/rake:22:in `<main>'
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:

(See full trace by running task with --trace)
Snorby setup failed due to error. Attempting patch for later versions of MySQL...
rake aborted!
There was an error while trying to load the gem 'devise'.
Gem Load Error is: ActiveSupport::Duration can't be coerced into Integer
Backtrace for gem load error is:
/usr/local/rvm/gems/ruby-2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:50:in `*'
/usr/local/rvm/gems/ruby-2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:50:in `days'
/usr/local/rvm/gems/ruby-2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:55:in `weeks'
/usr/local/rvm/gems/ruby-2.4.0/gems/devise-1.5.4/lib/devise.rb:121:in `<module:Devise>'
/usr/local/rvm/gems/ruby-2.4.0/gems/devise-1.5.4/lib/devise.rb:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/var/www/snorby/config/application.rb:12:in `<top (required)>'
/var/www/snorby/Rakefile:4:in `require'
/var/www/snorby/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/local/rvm/gems/ruby-2.4.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/bin/rake:22:in `load'
/usr/local/rvm/gems/ruby-2.4.0/bin/rake:22:in `<main>'
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:

(See full trace by running task with --trace)
```

Do you know how I can fix this and finish the installer?

**Comment by dustinmhorvath** [comment]
I've been looking into this for a few days now. It generally seemed to be a problem with backward compatibility with ruby and some gems being installed. For *now*, I've gone ahead and locked the Ruby version to 2.2.6, as that was the last known working version. At the moment, this fixes the issue you've raised here. That said, there are problems with passenger being able to load correctly on a page request that I'm currently looking into, but will be filed as a separate issue.
